# Generated by Django 6.0.4 on 2026-05-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject_attendance_reason_attendance_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', '✅ Keldi'), ('late', '🕒 Kechikdi'), ('excused', '📄 Sababli kelmadi'), ('absent', '❌ Sababsiz kelmadi')], max_length=20),
        ),
    ]
