# Generated by Django 6.0.4 on 2026-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
