# Generated by Django 6.0.4 on 2026-05-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_date_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'week')},
        ),
    ]
